version: "3.8"
services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/server:cached
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: development
