version: "3.8"
services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/server:cached
    tty: true
    stdin_open: true
    depends_on:
      - db
    env_file:
      - ./server/.env.local

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signapay_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
